name: opticalc_pro
description: Sistema profissional para Optometria e Otica desenvolvido em Flutter.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: any
  cloud_functions: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  intl: any
  provider: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
